// apps/ionic-react/src/components/widgets/loading.widget.tsx
import React from 'react';
import './loading.widget.scss';

export function LoadingWidget({ diameter = 80, stroke = 2.5 }: { diameter?: number; stroke?: number }) {
	return (
		<div data-loader>
			<svg style={{ width: `${diameter}px`, height: `${diameter}px` }} viewBox="25 25 50 50" className="spinner" role="presentation" aria-hidden="true">
				<circle style={{ strokeWidth: `${stroke}px` }} cx="50" cy="50" r="20" className="circle"></circle>
			</svg>
		</div>
	);
}

// apps/angular/src/app/components/widgets/loading/loading.widget.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';

@Component({
	standalone: false,
	encapsulation: ViewEncapsulation.None,
	selector: 'app-loading-widget',
	templateUrl: './loading.widget.html',
	styleUrls: ['./loading.widget.scss'],
	host: {
		'data-loader': '',
		'data-widget': 'loading',
	},
})
export class LoadingWidget {
	@Input() diameter: number = 80;
	@Input() stroke: number = 2.5;
}
