// apps/ionic-angular/src/app/pages/login/login.page.ts
/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-misused-promises */
import { Component, OnDestroy, OnInit, SkipSelf } from '@angular/core';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { Capacitor, type PluginListenerHandle } from '@capacitor/core';
import { DefaultWebViewOptions, InAppBrowser } from '@capacitor/inappbrowser';
import { redirectUrlHandler } from '@strivacity/sdk-core/utils/handlers';
import { SDKOptions, StrivacityAuthService, FallbackError, StyLoginRenderer, LoginFlowState, type ExtraRequestArgs } from '@strivacity/sdk-angular';
import { type ImportMeta } from '../../app.config';
import { widgets } from '../../components/widgets';

@Component({
	standalone: true,
	imports: [StyLoginRenderer],
	selector: 'app-login-page',
	templateUrl: './login.page.html',
})
export class LoginPage implements OnInit, OnDestroy {
	readonly widgets = widgets;
	readonly subscription = new Subscription();
	shortAppId: string | null = null;
	sessionId: string | null = null;
	options: SDKOptions;
	extraParams: ExtraRequestArgs = {
		loginHint: (import.meta as unknown as ImportMeta).env.VITE_LOGIN_HINT,
		acrValues: (import.meta as unknown as ImportMeta).env.VITE_ACR_VALUES ? (import.meta as unknown as ImportMeta).env.VITE_ACR_VALUES.split(' ') : undefined,
		uiLocales: (import.meta as unknown as ImportMeta).env.VITE_UI_LOCALES ? (import.meta as unknown as ImportMeta).env.VITE_UI_LOCALES.split(' ') : undefined,
		audiences: (import.meta as unknown as ImportMeta).env.VITE_AUDIENCES ? (import.meta as unknown as ImportMeta).env.VITE_AUDIENCES.split(' ') : undefined,
	};

	constructor(
		protected router: Router,
		@SkipSelf() protected strivacityAuthService: StrivacityAuthService,
	) {
		this.options = this.strivacityAuthService.options;

		if (window.location.search !== '') {
			const url = new URL(window.location.href);
			this.shortAppId = url.searchParams.get('short_app_id');
			this.sessionId = url.searchParams.get('session_id');
			url.search = '';
			history.replaceState({}, '', url.toString());
		}
	}

	ngOnInit() {
		if (this.options?.mode === 'redirect') {
			this.subscription.add(
				this.strivacityAuthService.login(this.extraParams).subscribe({
					next: async () => {
						if (Capacitor.getPlatform() !== 'web') {
							const params = (await this.options.callbackHandler!(this.options.redirectUri, this.options.responseMode || 'fragment')) as Record<string, string>;
							await this.strivacityAuthService.sdk.tokenExchange(params);
							await this.router.navigateByUrl('/profile');
						}
					},
					error: (error: any) => this.onError(error),
				}),
			);
		} else if (this.options?.mode === 'popup') {
			this.subscription.add(
				this.strivacityAuthService.login(this.extraParams).subscribe({
					next: async () => {
						await this.router.navigateByUrl('/profile');
					},
					error: (error: any) => this.onError(error),
				}),
			);
		}
	}

	ngOnDestroy() {
		this.subscription.unsubscribe();
	}

	async onLogin() {
		await this.router.navigateByUrl('/profile');
	}

	async onFallback(error: FallbackError) {
		if (error.url) {
			if (Capacitor.getPlatform() === 'web') {
				return redirectUrlHandler(error.url.toString());
			} else {
				await InAppBrowser.openInWebView({ url: error.url.toString(), options: DefaultWebViewOptions });

				// eslint-disable-next-line no-async-promise-executor
				const params = await new Promise<Record<string, string>>(async (resolve, reject) => {
					let navigationListener: PluginListenerHandle | null = null;
					let finishListener: PluginListenerHandle | null = null;
					let userCancelled = true;

					const cleanupListeners = async () => {
						if (navigationListener) {
							await navigationListener.remove();
							navigationListener = null;
						}

						if (finishListener) {
							await finishListener.remove();
							finishListener = null;
						}
					};

					try {
						navigationListener = await InAppBrowser.addListener('browserPageNavigationCompleted', async (event) => {
							const navigatedUrl = event.url;

							if (navigatedUrl && navigatedUrl.startsWith(this.options.redirectUri)) {
								try {
									const urlInstance = new URL(navigatedUrl);
									const dataString = this.options.responseMode === 'query' ? urlInstance.search : urlInstance.hash;
									const params = Object.fromEntries(new URLSearchParams(dataString.slice(1)));

									userCancelled = false;
									await InAppBrowser.close();
									resolve(params);
								} catch (error) {
									await InAppBrowser.close();
									reject(error);
								}
							}
						});
						finishListener = await InAppBrowser.addListener('browserClosed', async () => {
							await cleanupListeners();

							if (userCancelled) {
								reject(new Error('InAppBrowser flow cancelled by user.'));
							}
						});
					} catch (error) {
						reject(error);
					}
				});

				if (params.session_id) {
					await this.router.navigateByUrl(`/callback?session_id=${params.session_id}`);
				} else {
					await this.strivacityAuthService.sdk.tokenExchange(params);
					await this.router.navigateByUrl('/profile');
				}
			}
		} else {
			alert(error);
		}
	}

	onClose() {
		location.reload();
	}

	onError(error: any) {
		alert(error);
	}

	onGlobalMessage(message: string) {
		alert(message);
	}

	onBlockReady(_events: { previousState: LoginFlowState; state: LoginFlowState }) {
		// You can handle block ready events here
	}
}

// apps/ionic-vue/src/pages/login.page.vue
<!-- eslint-disable no-async-promise-executor, @typescript-eslint/no-misused-promises -->
<script lang="ts" setup>
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { Capacitor, type PluginListenerHandle } from '@capacitor/core';
import { DefaultWebViewOptions, InAppBrowser } from '@capacitor/inappbrowser';
import { redirectUrlHandler } from '@strivacity/sdk-core/utils/handlers';
import { FallbackError, useStrivacity, type LoginFlowState, type ExtraRequestArgs } from '@strivacity/sdk-vue';
import { widgets } from '../components/widgets';

const router = useRouter();
const { sdk, login } = useStrivacity();
const sessionId = ref<string | null>(null);

const extraParams: ExtraRequestArgs = {
	loginHint: import.meta.env.VITE_LOGIN_HINT,
	acrValues: import.meta.env.VITE_ACR_VALUES ? import.meta.env.VITE_ACR_VALUES.split(' ') : undefined,
	uiLocales: import.meta.env.VITE_UI_LOCALES ? import.meta.env.VITE_UI_LOCALES.split(' ') : undefined,
	audiences: import.meta.env.VITE_AUDIENCES ? import.meta.env.VITE_AUDIENCES.split(' ') : undefined,
};

if (location.search !== '') {
	const url = new URL(window.location.href);
	sessionId.value = url.searchParams.get('session_id');

	url.search = '';
	history.replaceState({}, '', url.toString());
}

onMounted(async () => {
	if (sdk.options.mode === 'redirect') {
		await login(extraParams);

		if (Capacitor.getPlatform() !== 'web') {
			const params = (await sdk.options.callbackHandler!(sdk.options.redirectUri, sdk.options.responseMode || 'fragment')) as Record<string, string>;
			await sdk.tokenExchange(params);
			await router.push('/profile');
		}
	} else if (sdk.options.mode === 'popup') {
		await login(extraParams);
		await router.push('/profile');
	}
});

const onLogin = async () => {
	await router.push('/profile');
};
const onFallback = async (error: FallbackError) => {
	if (error.url) {
		if (Capacitor.getPlatform() === 'web') {
			return redirectUrlHandler(error.url.toString());
		} else {
			await InAppBrowser.openInWebView({ url: error.url.toString(), options: DefaultWebViewOptions });

			const params = await new Promise<Record<string, string>>(async (resolve, reject) => {
				let navigationListener: PluginListenerHandle | null = null;
				let finishListener: PluginListenerHandle | null = null;
				let userCancelled = true;

				const cleanupListeners = async () => {
					if (navigationListener) {
						await navigationListener.remove();
						navigationListener = null;
					}

					if (finishListener) {
						await finishListener.remove();
						finishListener = null;
					}
				};

				try {
					navigationListener = await InAppBrowser.addListener('browserPageNavigationCompleted', async (event) => {
						const navigatedUrl = event.url;

						if (navigatedUrl && navigatedUrl.startsWith(sdk.options.redirectUri)) {
							try {
								const urlInstance = new URL(navigatedUrl);
								const dataString = sdk.options.responseMode === 'query' ? urlInstance.search : urlInstance.hash;
								const params = Object.fromEntries(new URLSearchParams(dataString.slice(1)));

								userCancelled = false;
								await InAppBrowser.close();
								resolve(params);
							} catch (error) {
								await InAppBrowser.close();
								reject(error);
							}
						}
					});
					finishListener = await InAppBrowser.addListener('browserClosed', async () => {
						await cleanupListeners();

						if (userCancelled) {
							reject(new Error('InAppBrowser flow cancelled by user.'));
						}
					});
				} catch (error) {
					reject(error);
				}
			});

			if (params.session_id) {
				await router.push(`/callback?session_id=${params.session_id}`);
			} else {
				await sdk.tokenExchange(params);
				await router.push('/profile');
			}
		}
	} else {
		alert(error);
	}
};
const onClose = () => {
	location.reload();
};
const onError = (error: string) => {
	alert(error);
};
const onGlobalMessage = (message: string) => {
	alert(message);
};
const onBlockReady = (_events: { previousState: LoginFlowState; state: LoginFlowState }) => {
	// You can handle block ready events here
};
</script>

<template>
	<section>
		<h1 v-if="sdk.options.mode === 'redirect'">Redirecting...</h1>
		<h1 v-else-if="sdk.options.mode === 'popup'">Loading...</h1>
		<Suspense v-else-if="sdk.options.mode === 'native'">
			<template #default>
				<StyLoginRenderer
					:params="extraParams"
					:widgets="widgets"
					:session-id="sessionId"
					@fallback="onFallback"
					@close="onClose"
					@login="onLogin"
					@error="onError"
					@global-message="onGlobalMessage"
					@block-ready="onBlockReady"
				/>
			</template>
			<template #fallback>
				<span>Loading...</span>
			</template>
		</Suspense>
	</section>
</template>

<style lang="scss">
.login-renderer {
	margin: 0 auto;
	width: 360px;
}
</style>
