// apps/vue/src/pages/entry.page.vue
<script lang="ts" setup>
import { onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useStrivacity } from '@strivacity/sdk-vue';

const router = useRouter();
const { entry } = useStrivacity();

onMounted(async () => {
	try {
		const data = await entry();

		if (data && Object.keys(data).length > 0) {
			await router.push(`/callback?${new URLSearchParams(data).toString()}`);
		} else {
			await router.push('/');
		}
	} catch (error) {
		alert(error);
		await router.push('/');
	}
});
</script>

<template>
	<section>
		<h1>Redirecting...</h1>
	</section>
</template>

// apps/angular/src/app/pages/entry/entry.page.ts
import { Component, SkipSelf } from '@angular/core';
import { Router } from '@angular/router';
import { StrivacityAuthService } from '@strivacity/sdk-angular';

@Component({
	standalone: false,
	selector: 'app-entry-page',
	templateUrl: './entry.page.html',
})
export class EntryPage {
	constructor(
		protected router: Router,
		@SkipSelf() protected strivacityAuthService: StrivacityAuthService,
	) {}

	ngOnInit() {
		this.strivacityAuthService.entry().subscribe({
			next: (data) => {
				if (data && Object.keys(data).length > 0) {
					void this.router.navigate([`/callback`], { queryParams: new URLSearchParams(data) });
				} else {
					void this.router.navigate(['/']);
				}
			},
			error: (error) => {
				alert(error);
				void this.router.navigate(['/']);
			},
		});
	}
}
