// apps/next/components/auth/native/widgets/LayoutWidget.tsx
import type { SubmitEvent, ReactNode } from 'react';
import type { LayoutWidget } from '@strivacity/sdk-next/client';
import { useNativeLoginContext } from '@strivacity/sdk-next/client';

type LayoutProps = {
	formId: string;
	type: LayoutWidget['type'];
	tag?: 'div' | 'form';
	children?: ReactNode;
};

export default function Layout({ formId, type, tag = 'div', children }: LayoutProps) {
	const { loading, submitForm } = useNativeLoginContext();
	const disabled = !!loading;

	const onSubmit = (event: SubmitEvent) => {
		event.preventDefault();

		if (disabled) {
			return;
		}

		void submitForm(formId);
	};

	if (tag === 'form') {
		return (
			<form data-widget="layout" data-type={type} data-form-id={formId} onSubmit={onSubmit}>
				{children}
			</form>
		);
	}

	return (
		<div data-widget="layout" data-type={type} data-form-id={formId}>
			{children}
		</div>
	);
}

// apps/sveltekit/src/lib/components/auth/native/widgets/LayoutWidget.svelte
<script lang="ts">
	import type { LayoutWidget } from '@strivacity/sdk-svelte/client';
	import type { Snippet } from 'svelte';
	import { useNativeLoginContext } from '@strivacity/sdk-svelte/client';

	let { formId, type, tag = 'div', children }: { formId: string; type: LayoutWidget['type']; tag?: string; children: Snippet } = $props();

	const context = useNativeLoginContext();
	const disabled = $derived(context.loading);

	async function onSubmit() {
		if (disabled) {
			return;
		}

		await context.submitForm(formId);
	}
</script>

<svelte:element
	this={tag}
	data-widget="layout"
	data-type={type}
	data-form-id={formId}
	onsubmit={(e) => {
		e.preventDefault();
		void onSubmit();
	}}
>
	{@render children()}
</svelte:element>
