// apps/solidstart/src/routes/entry.tsx
import { createEffect } from 'solid-js';
import { useNavigate } from '@solidjs/router';
import type { NativeFlow } from '@strivacity/sdk-solid/client';
import { useStrivacity } from '@strivacity/sdk-solid/client';

export default function Entry() {
	const ctx = useStrivacity<NativeFlow>();
	const navigate = useNavigate();

	createEffect(
		() => ctx.loading(),
		(loading) => {
			if (loading) {
				return;
			}

			ctx
				.entry()
				.then((params) => {
					const url = new URL('/login', globalThis.location.origin);
					url.search = new URLSearchParams(params).toString();
					globalThis.location.href = url.toString();
				})
				.catch((error) => {
					navigate(`/error?message=${encodeURIComponent(error instanceof Error ? error.message : 'Unknown error')}`);
				});
		},
	);

	return null;
}

// apps/react/src/pages/Entry.tsx
import type { NativeFlow } from '@strivacity/sdk-react';
import { useStrivacity } from '@strivacity/sdk-react';
import { useEffect } from 'react';
import { useNavigate } from 'react-router';

export default function Entry() {
	const { loading, sdk, entry } = useStrivacity<NativeFlow>();
	const navigate = useNavigate();

	useEffect(() => {
		if (loading) {
			return;
		}

		entry()
			.then((params) => {
				const url = new URL('/login', globalThis.location.origin);
				url.search = new URLSearchParams(params).toString();
				globalThis.location.href = url.toString();
			})
			.catch((error) => {
				void navigate(`/error?message=${encodeURIComponent(error instanceof Error ? error.message : 'Unknown error')}`);
			});
	}, [loading, sdk, entry]);

	return null;
}
