// apps/angular/src/app/pages/callback/callback.page.ts
import { Component, SkipSelf } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { type RedirectFlow, StrivacityAuthService } from '@strivacity/sdk-angular';

@Component({
	standalone: true,
	selector: 'app-callback-page',
	templateUrl: './callback.page.html',
})
export class CallbackPage {
	readonly subscription = new Subscription();
	readonly query = Object.fromEntries(new URLSearchParams(globalThis.window.location.search));

	constructor(
		protected route: ActivatedRoute,
		protected router: Router,
		@SkipSelf() protected strivacityAuthService: StrivacityAuthService<RedirectFlow>,
	) {}

	ngOnInit(): void {
		this.subscription.add(
			this.strivacityAuthService.handleCallback().subscribe({
				next: () => {
					this.router.navigateByUrl('/profile');
				},
			}),
		);
	}

	ngOnDestroy(): void {
		this.subscription.unsubscribe();
	}
}

// apps/web-component/src/pages/callback.page.ts
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { state } from 'lit/decorators/state.js';

@customElement('page-callback')
export class CallbackPage extends LitElement {
	@state() query = Object.fromEntries(new URLSearchParams(globalThis.window.location.search));

	async connectedCallback(): Promise<void> {
		super.connectedCallback();

		try {
			await globalThis.sdk.handleCallback();
			location.href = '/profile';
		} catch {}
	}

	render() {
		return this.query.error
			? html`
					<h1>Error in authentication</h1>
					<div>
						<h4>${this.query.error}</h4>
						<p>${this.query.error_description}</p>
					</div>
				`
			: html`
					<h1>Logging in...</h1>
				`;
	}
}
