// apps/vue/src/pages/profile.page.vue
<script setup lang="ts">
import { useStrivacity } from '@strivacity/sdk-vue';

const { accessToken, accessTokenExpired, accessTokenExpirationDate, idTokenClaims, refreshToken } = useStrivacity();
</script>

<template>
	<section>
		<dl>
			<dt><strong>accessToken</strong></dt>
			<dd>
				<pre>{{ JSON.stringify(accessToken) }}</pre>
			</dd>
			<dt><strong>refreshToken</strong></dt>
			<dd>
				<pre>{{ JSON.stringify(refreshToken) }}</pre>
			</dd>
			<dt><strong>accessTokenExpired</strong></dt>
			<dd>
				<pre>{{ JSON.stringify(accessTokenExpired) }}</pre>
			</dd>
			<dt><strong>accessTokenExpirationDate</strong></dt>
			<dd>
				<pre>{{ accessTokenExpirationDate ? new Date(accessTokenExpirationDate * 1000).toLocaleString() : JSON.stringify(null) }}</pre>
			</dd>
			<dt><strong>claims</strong></dt>
			<dd>
				<pre>{{ JSON.stringify(idTokenClaims, null, 2) }}</pre>
			</dd>
		</dl>
	</section>
</template>

// apps/web-component/src/pages/profile.page.ts
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('page-profile')
export class ProfilePage extends LitElement {
	render() {
		return html`
			<dl>
				<dt><strong>accessToken</strong></dt>
				<dd>
					<pre>${JSON.stringify(globalThis.sdk.accessToken)}</pre>
				</dd>
				<dt><strong>refreshToken</strong></dt>
				<dd>
					<pre>${JSON.stringify(globalThis.sdk.refreshToken)}</pre>
				</dd>
				<dt><strong>accessTokenExpired</strong></dt>
				<dd>
					<pre>${JSON.stringify(globalThis.sdk.accessTokenExpired)}</pre>
				</dd>
				<dt><strong>accessTokenExpirationDate</strong></dt>
				<dd>
					<pre>
${globalThis.sdk.accessTokenExpirationDate ? new Date(globalThis.sdk.accessTokenExpirationDate * 1000).toLocaleString() : JSON.stringify(null)}</pre
					>
				</dd>
				<dt><strong>claims</strong></dt>
				<dd>
					<pre>${JSON.stringify(globalThis.sdk.idTokenClaims, null, 2)}</pre>
				</dd>
			</dl>
		`;
	}
}
