// apps/preact/src/components/auth/redirect/RedirectLogin.tsx
import { useEffect } from 'preact/compat';
import type { PopupFlow } from '@strivacity/sdk-preact';
import { useStrivacity } from '@strivacity/sdk-preact';
import { extraParams } from '../';

export default function RedirectLogin({ flowType }: { flowType: 'login' | 'register' }) {
	const { loading, login, register } = useStrivacity<PopupFlow>();

	useEffect(() => {
		if (loading) {
			return;
		}

		if (flowType === 'register') {
			void register(extraParams);
		} else {
			void login(extraParams);
		}
	}, [loading, flowType, login, register]);

	return (
		<section>
			<p>Loading...</p>
		</section>
	);
}

// apps/solidstart/src/components/auth/redirect/RedirectLogin.tsx
import type { PopupFlow } from '@strivacity/sdk-solid/client';
import { onSettled } from 'solid-js';
import { useStrivacity } from '@strivacity/sdk-solid/client';
import { extraParams } from '../../../options';

export default function RedirectLogin(props: { flowType: 'login' | 'register' }) {
	const ctx = useStrivacity<PopupFlow>();

	onSettled(() => {
		if (props.flowType === 'register') {
			void ctx.register(extraParams);
		} else {
			void ctx.login(extraParams);
		}
	});

	return (
		<section>
			<p>Loading...</p>
		</section>
	);
}
