// apps/svelte/src/components/static.widget.svelte
<script lang="ts">
	import type { StaticWidget } from '@strivacity/sdk-svelte';

	let { formId, config }: { formId: string; config: StaticWidget } = $props();
</script>

{#if config.render?.type === 'html'}
	<div data-widget="static" data-form-id={formId} data-widget-id={config.id}>
		<!-- eslint-disable-next-line svelte/no-at-html-tags -->
		{@html config.value}
	</div>
{:else}
	<div data-widget="static" data-form-id={formId} data-widget-id={config.id}>
		{config.value}
	</div>
{/if}

<style lang="scss">
	:global {
		[data-widget='static'] {
			text-align: center;

			p {
				margin: 0;
			}

			&[data-widget-id='section-title'] {
				font-size: 1.5rem;
				font-weight: 600;
			}

			&:not(:has(+ [data-widget='submit'])) {
				margin-block-end: 0.5rem;
			}
		}
	}
</style>

// apps/vue/src/components/widgets/static.widget.vue
<script lang="ts" setup>
import type { StaticWidget } from '@strivacity/sdk-core';

defineProps<{ formId: string; config: StaticWidget }>();
</script>

<template>
	<div v-if="config.render?.type === 'html'" data-widget="static" :data-form-id="formId" :data-widget-id="config.id" v-html="config.value"></div>
	<div v-else data-widget="static" :data-form-id="formId" :data-widget-id="config.id">{{ config.value }}</div>
</template>

<style lang="scss" scoped>
[data-widget='static'] {
	text-align: center;

	:deep(p) {
		margin: 0;
	}

	&[data-widget-id='section-title'] {
		font-size: 1.5rem;
		font-weight: 600;
	}

	&:not(:has(+ [data-widget='submit'])) {
		margin-block-end: 0.5rem;
	}
}
</style>
