// apps/vue/src/App.vue
<script setup lang="ts">
import { useStrivacity } from '@strivacity/sdk-vue';
import { computed } from 'vue';
import { RouterLink, RouterView } from 'vue-router';

const { isAuthenticated, idTokenClaims } = useStrivacity();

const name = computed(() => (isAuthenticated.value ? `${idTokenClaims.value?.given_name ?? ''} ${idTokenClaims.value?.family_name ?? ''}`.trim() : null));
</script>

<template>
	<header>
		<div>
			<strong v-if="isAuthenticated">Welcome, {{ name }}!</strong>
		</div>
		<div>
			<RouterLink to="/" data-button="home">Home</RouterLink>
			<template v-if="isAuthenticated">
				<RouterLink to="/profile" data-button="profile">Profile</RouterLink>
				<RouterLink to="/revoke" data-button="revoke">Revoke</RouterLink>
				<RouterLink to="/logout" data-button="logout">Logout</RouterLink>
			</template>
			<template v-else>
				<RouterLink to="/login" data-button="login">Login</RouterLink>
				<RouterLink to="/register" data-button="register">Register</RouterLink>
			</template>
		</div>
	</header>
	<RouterView />
</template>

// apps/preact/src/components/App.tsx
import type { ComponentChildren } from 'preact';
import { useStrivacity } from '@strivacity/sdk-preact';

export function App({ children }: { children: ComponentChildren }) {
	const { isAuthenticated, idTokenClaims } = useStrivacity();
	const name = isAuthenticated ? `${idTokenClaims?.given_name} ${idTokenClaims?.family_name}` : null;

	return (
		<div id="app">
			<header>
				<div>{isAuthenticated ? <strong>Welcome, {name}!</strong> : null}</div>
				<div>
					<a href="/" data-button="home">
						Home
					</a>
					{isAuthenticated ? (
						<>
							<a href="/profile" data-button="profile">
								Profile
							</a>
							<a href="/revoke" data-button="revoke">
								Revoke
							</a>
							<a href="/logout" data-button="logout">
								Logout
							</a>
						</>
					) : (
						<>
							<a href="/login" data-button="login">
								Login
							</a>
							<a href="/register" data-button="register">
								Register
							</a>
						</>
					)}
				</div>
			</header>
			{children}
		</div>
	);
}
