// apps/ionic-react/src/components/widgets/passcode.widget.tsx
import React, { useContext, useMemo } from 'react';
import type { PasscodeWidget } from '@strivacity/sdk-core';
import { NativeFlowContext } from '@strivacity/sdk-react';
import './passcode.widget.scss';

export function PasscodeWidget({ formId, config }: { formId: string; config: PasscodeWidget }) {
	const context = useContext(NativeFlowContext);
	const disabled = useMemo(() => !!context?.loading, [context?.loading]);
	const errorMessage = context?.messages[formId]?.[config.id]?.text;

	const onInput = (event: React.FormEvent<HTMLInputElement>) => {
		const inputElement = event.target as HTMLInputElement;
		inputElement.value = inputElement.value.replace(/\D/g, '');
	};

	const onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
		if (disabled) {
			return;
		}

		context?.setFormValue(formId, config.id, event.target.value);
	};

	const onKeyDown = async (event: React.KeyboardEvent<HTMLInputElement>) => {
		if (disabled || event.key !== 'Enter') {
			return;
		}

		event.stopPropagation();

		const input = event.target as HTMLInputElement;

		if (input.reportValidity()) {
			context?.setFormValue(formId, config.id, input.value);
			await context?.submitForm(formId);
		}
	};

	return (
		<div data-widget="passcode" data-form-id={formId} data-widget-id={config.id}>
			{config.label && (
				<label htmlFor={config.id} className="label">
					{config.label}
				</label>
			)}
			<input
				id={config.id}
				name={config.id}
				type={config.type}
				readOnly={disabled}
				minLength={config.validator?.length}
				maxLength={config.validator?.length}
				autoComplete="off"
				inputMode="numeric"
				size={1}
				onInput={(e) => onInput(e)}
				onChange={(e) => onChange(e)}
				onKeyDown={(e) => void onKeyDown(e)}
			/>
			{errorMessage && <small className="error">{errorMessage}</small>}
		</div>
	);
}

// apps/sveltekit/src/lib/components/widgets/PasscodeWidget.svelte
<script lang="ts">
	import type { PasscodeWidget } from '@strivacity/sdk-svelte/client';
	import { useNativeLoginContext } from '@strivacity/sdk-svelte/client';

	let { formId, config }: { formId: string; config: PasscodeWidget } = $props();

	const context = useNativeLoginContext();
	const disabled = $derived(context.loading);
	const errorMessage = $derived(context.messages[formId]?.[config.id]?.text);
	const validator = $derived(config.validator);

	function onInput(event: Event) {
		const inputElement = event.target as HTMLInputElement;
		inputElement.value = inputElement.value.replace(/\D/g, '');
	}

	function onChange(event: Event) {
		if (disabled) {
			return;
		}

		context.setFormValue(formId, config.id, (event.target as HTMLInputElement).value);
	}

	async function onKeyDown(event: KeyboardEvent) {
		if (disabled) {
			return;
		}

		const input = event.target as HTMLInputElement;

		if (input.reportValidity()) {
			context.setFormValue(formId, config.id, (event.target as HTMLInputElement).value);
			await context.submitForm(formId);
		}
	}
</script>

<div data-widget="passcode" data-form-id={formId} data-widget-id={config.id}>
	{#if config.label}
		<label for={config.id} class="label">{config.label}</label>
	{/if}
	<input
		id={config.id}
		name={config.id}
		type={config.type}
		readonly={disabled}
		minlength={validator?.length}
		maxlength={validator?.length}
		autocomplete="off"
		inputmode="numeric"
		size="1"
		oninput={onInput}
		onchange={onChange}
		onkeydown={(e) => {
			if (e.key === 'Enter') {
				e.stopPropagation();
				void onKeyDown(e);
			}
		}}
	/>
	{#if errorMessage}
		<small class="error">{errorMessage}</small>
	{/if}
</div>
