// apps/ionic-react/src/components/widgets/submit.widget.tsx
import React, { useContext, useMemo } from 'react';
import type { SubmitWidget } from '@strivacity/sdk-core';
import { NativeFlowContext } from '@strivacity/sdk-react';
import './submit.widget.scss';

export function SubmitWidget({ formId, config }: { formId: string; config: SubmitWidget }) {
	const context = useContext(NativeFlowContext);
	const disabled = useMemo(() => !!context?.loading, [context?.loading]);

	const onSubmit = async (event: React.SyntheticEvent) => {
		event.preventDefault();

		if (disabled) {
			return;
		}

		const form = (event.target as HTMLElement).closest('form');

		if (form?.dataset.formId === formId) {
			form.requestSubmit();
		} else {
			await context?.submitForm(formId);
		}
	};

	return (
		<>
			{config.render?.type === 'button' ? (
				<button
					type="submit"
					disabled={disabled}
					style={{
						backgroundColor: config.render.bgColor ?? (config.render.hint?.variant === 'primary' ? `#5d21ab` : `#ffffff`),
						color: config.render.textColor ?? (config.render.hint?.variant === 'primary' ? `#ffffff` : `#5d21ab`),
					}}
					data-type="button"
					data-widget="submit"
					data-form-id={formId}
					data-widget-id={config.id}
					onClick={(e) => void onSubmit(e)}
					onKeyDown={(e) => (['Enter', 'Space'].includes(e.code) ? void onSubmit(e) : undefined)}
				>
					{config.label}
				</button>
			) : (
				<a
					data-type="link"
					data-widget="submit"
					data-form-id={formId}
					data-widget-id={config.id}
					tabIndex={0}
					onClick={(e) => void onSubmit(e)}
					onKeyDown={(e) => (['Enter', 'Space'].includes(e.code) ? void onSubmit(e) : undefined)}
				>
					{config.label}
				</a>
			)}
		</>
	);
}

// apps/nuxt/app/components/auth/native/widgets/SubmitWidget.vue
<script lang="ts" setup>
import type { SubmitWidget } from '@strivacity/sdk-nuxt';
import { computed, useNativeLoginContext } from '#imports';

const props = defineProps<{ formId: string; config: SubmitWidget }>();

const { loading, submitForm } = useNativeLoginContext();
const disabled = computed(() => !!loading.value);

async function onSubmit(event: Event) {
	if (disabled.value) {
		return;
	}

	const form = (event.target as HTMLElement).closest('form');

	if (form?.dataset.formId === props.formId) {
		form.requestSubmit();
	} else {
		await submitForm(props.formId);
	}
}
</script>

<template>
	<button
		v-if="config.render?.type === 'button'"
		type="submit"
		:disabled="disabled"
		:style="{
			backgroundColor: config.render.bgColor ?? (config.render.hint?.variant === 'primary' ? `#5d21ab` : `#ffffff`),
			color: config.render.textColor ?? (config.render.hint?.variant === 'primary' ? `#ffffff` : `#5d21ab`),
		}"
		data-widget="submit"
		data-type="button"
		:data-form-id="formId"
		:data-widget-id="config.id"
		@click.prevent="onSubmit($event)"
		@keydown.enter="onSubmit($event)"
		@keydown.space="onSubmit($event)"
	>
		{{ config.label }}
	</button>
	<a
		v-else
		data-widget="submit"
		data-type="link"
		:data-form-id="formId"
		:data-widget-id="config.id"
		tabindex="0"
		@click.prevent="onSubmit($event)"
		@keydown.enter="onSubmit($event)"
		@keydown.space="onSubmit($event)"
	>
		{{ config.label }}
	</a>
</template>
