// apps/sveltekit/src/lib/components/auth/popup/PopupLogin.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { resolve } from '$app/paths';
	import { useStrivacity } from '@strivacity/sdk-svelte/client';
	import { extraParams } from '../';

	let { flowType }: { flowType: 'login' | 'register' } = $props();

	const ctx = useStrivacity();

	onMount(async () => {
		try {
			if (flowType === 'register') {
				await ctx.register(extraParams);
			} else {
				await ctx.login(extraParams);
			}

			globalThis.location.href = '/profile';
		} catch (error) {
			globalThis.location.href = `${resolve('/error')}?error_description=${encodeURIComponent(error.message)}`;
		}
	});
</script>

<section>Loading...</section>

// apps/solidstart/src/components/auth/popup/PopupLogin.tsx
import type { PopupFlow } from '@strivacity/sdk-solid/client';
import { onSettled } from 'solid-js';
import { useStrivacity } from '@strivacity/sdk-solid/client';
import { extraParams } from '../../../options';

export default function PopupLogin(props: { flowType: 'login' | 'register' }) {
	const ctx = useStrivacity<PopupFlow>();

	onSettled(() => {
		(props.flowType === 'register' ? ctx.register(extraParams) : ctx.login(extraParams))
			.then(() => {
				globalThis.location.href = '/profile';
			})
			.catch((error) => {
				globalThis.location.href = `/error?error_description=${encodeURIComponent(error.message)}`;
			});
	});

	return (
		<section>
			<p>Loading...</p>
		</section>
	);
}
