// apps/preact/src/components/profile/Session.tsx
import { useStrivacity } from '@strivacity/sdk-preact';
import { DateTime } from 'luxon';
import { route } from 'preact-router';

export function Session() {
	const { loading, sdk, refresh } = useStrivacity();
	const session = sdk?.session;

	if (loading || !session) {
		return null;
	}

	function handleRefresh() {
		refresh()
			.then(() => {
				globalThis.location.reload();
			})
			.catch((error) => {
				route(`/error?message=${encodeURIComponent(error instanceof Error ? error.message : 'Unknown error')}`);
			});
	}

	return (
		<section>
			<h2>Session</h2>
			<dl>
				<dt>expires</dt>
				<dd>{session.expires_at ? DateTime.fromMillis(session.expires_at * 1000).toLocaleString(DateTime.DATETIME_MED_WITH_SECONDS) : '-'}</dd>

				<dt>access token</dt>
				<dd>{session.access_token}</dd>

				<dt>refresh token</dt>
				<dd>{session.refresh_token}</dd>

				{session.refresh_token && (
					<>
						<dt></dt>
						<dd>
							<button onClick={handleRefresh}>Refresh</button>
						</dd>
					</>
				)}

				<dt>account id</dt>
				<dd>{session.claims?.sub ?? '-'}</dd>

				<dt>claims</dt>
				<dd>
					<pre>{JSON.stringify(session.claims, null, 2)}</pre>
				</dd>
			</dl>
		</section>
	);
}

// apps/vue/src/components/profile/Session.vue
<script setup lang="ts">
import { useStrivacity } from '@strivacity/sdk-vue';
import { useRouter } from 'vue-router';
import { DateTime } from 'luxon';

const { sdk, refresh } = useStrivacity();
const router = useRouter();

async function handleRefresh() {
	try {
		await refresh();
		globalThis.location.reload();
	} catch (error) {
		void router.push(`/error?message=${encodeURIComponent(error instanceof Error ? error.message : 'Unknown error')}`);
	}
}
</script>

<template>
	<section>
		<h2>Session</h2>
		<dl>
			<dt>expires</dt>
			<dd>{{ sdk.session?.expires_at ? DateTime.fromMillis(sdk.session?.expires_at * 1000).toLocaleString(DateTime.DATETIME_MED_WITH_SECONDS) : '-' }}</dd>

			<dt>access token</dt>
			<dd>{{ sdk.session?.access_token }}</dd>

			<dt>refresh token</dt>
			<dd>{{ sdk.session?.refresh_token }}</dd>

			<template v-if="sdk.session?.refresh_token">
				<dt></dt>
				<dd><button @click="handleRefresh">Refresh</button></dd>
			</template>

			<dt>account id</dt>
			<dd>{{ sdk.session?.claims?.sub ?? '-' }}</dd>

			<dt>claims</dt>
			<dd>
				<pre>{{ JSON.stringify(sdk.session?.claims, null, 2) }}</pre>
			</dd>
		</dl>
	</section>
</template>
