// apps/svelte/src/routes/revoke/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { browser } from '$app/environment';
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { useStrivacity } from '@strivacity/sdk-svelte';

	const { state, revoke } = useStrivacity();

	onMount(async () => {
		if (!browser) {
			return;
		}

		if (state.isAuthenticated) {
			await revoke();
		}

		await goto(resolve('/'));
	});
</script>

<section>
	<h1>Logging out...</h1>
</section>

// apps/next/src/app/revoke/page.tsx
'use client';

import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useStrivacity } from '@strivacity/sdk-next';

export default function Revoke() {
	const router = useRouter();
	const { isAuthenticated, revoke } = useStrivacity();

	useEffect(() => {
		// eslint-disable-next-line @typescript-eslint/no-floating-promises
		(async () => {
			if (isAuthenticated) {
				await revoke();
			}

			router.push('/');
		})();
	}, []);

	return (
		<section>
			<h1>Logging out...</h1>
		</section>
	);
}
