// apps/web-component/src/pages/callback.page.ts
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { state } from 'lit/decorators/state.js';

@customElement('page-callback')
export class CallbackPage extends LitElement {
	@state() query = Object.fromEntries(new URLSearchParams(globalThis.window.location.search));

	async connectedCallback(): Promise<void> {
		super.connectedCallback();

		try {
			await globalThis.sdk.handleCallback();
			location.href = '/profile';
		} catch {}
	}

	render() {
		return this.query.error
			? html`
					<h1>Error in authentication</h1>
					<div>
						<h4>${this.query.error}</h4>
						<p>${this.query.error_description}</p>
					</div>
				`
			: html`
					<h1>Logging in...</h1>
				`;
	}
}

// apps/vue/src/pages/callback.page.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useStrivacity } from '@strivacity/sdk-vue';

const router = useRouter();
const { handleCallback } = useStrivacity();

onMounted(async () => {
	try {
		await handleCallback();
		await router.push('/profile');
	} catch {}
});
</script>

<template>
	<section v-if="$route.query.error">
		<h1>Error in authentication</h1>
		<div>
			<h4>{{ $route.query.error }}</h4>
			<p>{{ $route.query.error_description }}</p>
		</div>
	</section>
	<section v-else>
		<h1>Logging in...</h1>
	</section>
</template>
