// apps/preact/src/pages/Entry.tsx
import type { NativeFlow } from '@strivacity/sdk-preact';
import { useStrivacity } from '@strivacity/sdk-preact';
import { useEffect } from 'preact/hooks';
import { route } from 'preact-router';

export default function Entry() {
	const { loading, sdk, entry } = useStrivacity<NativeFlow>();

	useEffect(() => {
		if (loading) {
			return;
		}

		if (!['embedded', 'native'].includes(sdk.options.mode)) {
			globalThis.location.href = '/login';
			return;
		}

		entry()
			.then((params) => {
				const url = new URL(sdk.options.loginUri, globalThis.location.origin);
				url.search = new URLSearchParams(params).toString();
				globalThis.location.href = url.toString();
			})
			.catch((error) => {
				route(`/error?message=${encodeURIComponent(error instanceof Error ? error.message : 'Unknown error')}`);
			});
	}, [loading, sdk]);

	return null;
}

// apps/vue/src/pages/Entry.vue
<script setup lang="ts">
import type { NativeFlow } from '@strivacity/sdk-vue';
import { useStrivacity } from '@strivacity/sdk-vue';
import { useRouter } from 'vue-router';
import { onMounted } from 'vue';

const { sdk, entry } = useStrivacity<NativeFlow>();
const router = useRouter();

onMounted(async () => {
	if (!['embedded', 'native'].includes(sdk.options.mode)) {
		return await router.push('/login');
	}

	try {
		const params = await entry();
		const url = new URL(sdk.options.loginUri, globalThis.location.origin);
		url.search = new URLSearchParams(params).toString();
		globalThis.location.href = url.toString();
	} catch (error) {
		void router.push(`/error?message=${encodeURIComponent(error instanceof Error ? error.message : 'Unknown error')}`);
		return;
	}
});
</script>
