// apps/web-component/src/pages/revoke.page.ts
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('page-revoke')
export class RevokePage extends LitElement {
	async connectedCallback(): Promise<void> {
		super.connectedCallback();

		try {
			await globalThis.sdk.revoke();
		} catch {
		} finally {
			location.href = '/';
		}
	}

	render() {
		return html`
			<h1>Logging out...</h1>
		`;
	}
}

// apps/vue/src/pages/revoke.page.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useStrivacity } from '@strivacity/sdk-vue';

const router = useRouter();
const { revoke } = useStrivacity();

onMounted(async () => {
	try {
		await revoke();
	} catch {
	} finally {
		await router.push('/');
	}
});
</script>

<template>
	<section>
		<h1>Logging out...</h1>
	</section>
</template>
