// apps/svelte/src/routes/entry/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { browser } from '$app/environment';
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { useStrivacity } from '@strivacity/sdk-svelte';

	const { entry } = useStrivacity();

	onMount(async () => {
		if (!browser) {
			return;
		}

		try {
			const data = await entry();

			if (data && Object.keys(data).length > 0) {
				// eslint-disable-next-line svelte/no-navigation-without-resolve
				await goto(`${resolve('/login')}?${new URLSearchParams(data).toString()}`);
			} else {
				await goto(resolve('/'));
			}
		} catch (error) {
			alert(error)
			await goto(resolve('/'));
		}
	});
</script>

<section>
	<h1>Redirecting...</h1>
</section>

// apps/remix/src/routes/entry.tsx
import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useStrivacity } from '@strivacity/sdk-remix';

export default function Entry() {
	const navigate = useNavigate();
	const { entry } = useStrivacity();

	useEffect(() => {
		// eslint-disable-next-line @typescript-eslint/no-floating-promises
		(async () => {
			try {
				const data = await entry();

				if (data && Object.keys(data).length > 0) {
					navigate(`/callback?${new URLSearchParams(data).toString()}`);
				} else {
					navigate('/');
				}
			} catch (error) {
				alert(error);
				navigate('/');
			}
		})();
	}, []);

	return (
		<section>
			<h1>Redirecting...</h1>
		</section>
	);
}
