// apps/vue/src/components/auth/native/widgets/LayoutWidget.vue
<script lang="ts" setup>
import { computed } from 'vue';
import { type LayoutWidget, useNativeLoginContext } from '@strivacity/sdk-vue';

const props = withDefaults(defineProps<{ formId: string; type: LayoutWidget['type']; tag?: string }>(), {
	tag: 'div',
});

const { loading, submitForm } = useNativeLoginContext();
const disabled = computed(() => !!loading.value);

async function onSubmit() {
	if (disabled.value) {
		return;
	}

	await submitForm(props.formId);
}
</script>

<template>
	<component :is="tag" data-widget="layout" :data-type="type" :data-form-id="formId" @submit.prevent="onSubmit()">
		<slot />
	</component>
</template>

// apps/react/src/components/auth/native/widgets/LayoutWidget.tsx
import type { SubmitEvent, ReactNode } from 'react';
import type { LayoutWidget } from '@strivacity/sdk-react';
import { useNativeLoginContext } from '@strivacity/sdk-react';

type LayoutProps = {
	formId: string;
	type: LayoutWidget['type'];
	tag?: 'div' | 'form';
	children?: ReactNode;
};

export default function Layout({ formId, type, tag = 'div', children }: LayoutProps) {
	const { loading, submitForm } = useNativeLoginContext();
	const disabled = !!loading;

	const onSubmit = (event: SubmitEvent) => {
		event.preventDefault();

		if (disabled) {
			return;
		}

		void submitForm(formId);
	};

	if (tag === 'form') {
		return (
			<form data-widget="layout" data-type={type} data-form-id={formId} onSubmit={onSubmit}>
				{children}
			</form>
		);
	}

	return (
		<div data-widget="layout" data-type={type} data-form-id={formId}>
			{children}
		</div>
	);
}
