// apps/ionic-react/src/components/App.tsx
import { useEffect, useState } from 'react';
import { Outlet, Link } from 'react-router';
import { useStrivacity } from '@strivacity/sdk-react';
import './App.css';

export const App = () => {
	const { loading, isAuthenticated, idTokenClaims } = useStrivacity();
	const [name, setName] = useState('');

	useEffect(() => {
		setName(`${idTokenClaims?.given_name ?? ''} ${idTokenClaims?.family_name ?? ''}`);
	}, [isAuthenticated, idTokenClaims]);

	return (
		<>
			<header>
				<div>{isAuthenticated ? <strong>Welcome, {name}!</strong> : loading ? <strong>Loading...</strong> : null}</div>
				<div>
					{!loading && (
						<>
							<Link to="/" data-button="home">
								Home
							</Link>
							{isAuthenticated ? (
								<>
									<Link to="/profile" data-button="profile">
										Profile
									</Link>
									<Link to="/revoke" data-button="revoke">
										Revoke
									</Link>
									<Link to="/logout" data-button="logout">
										Logout
									</Link>
								</>
							) : (
								<>
									<Link to="/login" data-button="login">
										Login
									</Link>
									<Link to="/register" data-button="register">
										Register
									</Link>
								</>
							)}
						</>
					)}
				</div>
			</header>
			<Outlet />
		</>
	);
};

// apps/angular-standalone/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { StrivacityAuthService } from '@strivacity/sdk-angular';

@Component({
	standalone: true,
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrl: './app.component.scss',
	providers: [StrivacityAuthService],
	imports: [RouterOutlet, RouterLink, RouterLinkActive],
})
export class AppComponent {
	loading = true;
	isAuthenticated = false;
	name = '';

	constructor(protected strivacityAuthService: StrivacityAuthService) {
		// eslint-disable-next-line @typescript-eslint/no-implied-eval
		new Function('url', 'return import(url)')(`${this.strivacityAuthService.sdk.options.issuer}/assets/components/bundle.js`);

		this.strivacityAuthService.session$.subscribe((session) => {
			this.loading = session.loading;
			this.isAuthenticated = session.isAuthenticated;
			this.name = `${session.idTokenClaims?.given_name ?? ''} ${session.idTokenClaims?.family_name ?? ''}`;
		});
	}
}

<header>
	<div>
		@if (isAuthenticated) {
			<strong>Welcome, {{ name }}!</strong>
		} @else if (loading) {
			<strong>Loading...</strong>
		}
	</div>
	<div>
		<a routerLink="/" routerLinkActive="active" data-button="home">Home</a>
		@if (isAuthenticated) {
			<a routerLink="/profile" routerLinkActive="active" data-button="profile">Profile</a>
			<a routerLink="/revoke" routerLinkActive="active" data-button="revoke">Revoke</a>
			<a routerLink="/logout" routerLinkActive="active" data-button="logout">Logout</a>
		} @else {
			<a routerLink="/login" routerLinkActive="active" data-button="login">Login</a>
			<a routerLink="/register" routerLinkActive="active" data-button="register">Register</a>
		}
	</div>
</header>
<router-outlet />
