// apps/solidstart/src/components/auth/native/widgets/LayoutWidget.tsx
import type { ParentProps } from 'solid-js';
import { useNativeLoginContext } from '@strivacity/sdk-solid/client';

type LayoutProps = ParentProps<{
	formId?: string;
	type?: string;
	tag?: 'form' | 'div';
}>;

export default function Layout(props: LayoutProps) {
	const ctx = useNativeLoginContext();

	function onSubmit(event: SubmitEvent) {
		event.preventDefault();

		if (ctx.loading() || !props.formId) {
			return;
		}

		void ctx.submitForm(props.formId);
	}

	if (props.tag === 'form') {
		return (
			<form data-widget="layout" data-type={props.type} data-form-id={props.formId} onSubmit={onSubmit}>
				{props.children}
			</form>
		);
	}

	return (
		<div data-widget="layout" data-type={props.type} data-form-id={props.formId}>
			{props.children}
		</div>
	);
}

// apps/next/components/auth/native/widgets/LayoutWidget.tsx
import type { SubmitEvent, ReactNode } from 'react';
import type { LayoutWidget } from '@strivacity/sdk-next/client';
import { useNativeLoginContext } from '@strivacity/sdk-next/client';

type LayoutProps = {
	formId: string;
	type: LayoutWidget['type'];
	tag?: 'div' | 'form';
	children?: ReactNode;
};

export default function Layout({ formId, type, tag = 'div', children }: LayoutProps) {
	const { loading, submitForm } = useNativeLoginContext();
	const disabled = !!loading;

	const onSubmit = (event: SubmitEvent) => {
		event.preventDefault();

		if (disabled) {
			return;
		}

		void submitForm(formId);
	};

	if (tag === 'form') {
		return (
			<form data-widget="layout" data-type={type} data-form-id={formId} onSubmit={onSubmit}>
				{children}
			</form>
		);
	}

	return (
		<div data-widget="layout" data-type={type} data-form-id={formId}>
			{children}
		</div>
	);
}
