// apps/solidstart/src/components/auth/native/widgets/CheckboxWidget.tsx
import type { CheckboxWidget } from '@strivacity/sdk-solid/client';
import { createMemo } from 'solid-js';
import { useNativeLoginContext } from '@strivacity/sdk-solid/client';

export default function Checkbox(props: { formId: string; config: CheckboxWidget }) {
	const ctx = useNativeLoginContext();
	const disabled = createMemo(() => ctx.loading());
	const checked = createMemo(() => (ctx.forms()[props.formId]?.[props.config.id] as boolean) || props.config.value || false);
	const errorMessage = createMemo(() => ctx.messages()[props.formId]?.[props.config.id]?.text);

	function onChange(event: Event) {
		if (disabled()) {
			return;
		}

		ctx.setFormValue(props.formId, props.config.id, (event.currentTarget as HTMLInputElement).checked);
	}

	return (
		<div data-widget="checkbox" data-form-id={props.formId} data-widget-id={props.config.id}>
			<div>
				<input
					id={props.config.id}
					name={props.config.id}
					disabled={disabled()}
					required={props.config.validator?.required}
					checked={checked()}
					type="checkbox"
					size={1}
					onChange={onChange}
				/>
				{props.config.label && (
					<label for={props.config.id} class="label">
						{props.config.label}
					</label>
				)}
			</div>
			{errorMessage() && <small class="error">{errorMessage()}</small>}
		</div>
	);
}

// apps/preact/src/components/auth/native/widgets/CheckboxWidget.tsx
import type { ChangeEvent } from 'preact/compat';
import type { CheckboxWidget } from '@strivacity/sdk-preact';
import { useNativeLoginContext } from '@strivacity/sdk-preact';

export default function Checkbox({ formId, config }: { formId: string; config: CheckboxWidget }) {
	const { loading, forms, messages, setFormValue } = useNativeLoginContext();
	const disabled = !!loading;
	const checked = (forms[formId]?.[config.id] as boolean) || config.value || false;
	const errorMessage = messages[formId]?.[config.id]?.text;

	const onChange = (event: ChangeEvent<HTMLInputElement>) => {
		if (disabled) {
			return;
		}

		setFormValue(formId, config.id, event.currentTarget.checked);
	};

	return (
		<div data-widget="checkbox" data-form-id={formId} data-widget-id={config.id}>
			<div>
				<input
					id={config.id}
					name={config.id}
					disabled={disabled}
					required={config.validator?.required}
					checked={checked}
					type="checkbox"
					size={1}
					onChange={onChange}
				/>
				{config.label && (
					<label htmlFor={config.id} className="label">
						{config.label}
					</label>
				)}
			</div>
			{errorMessage && <small className="error">{errorMessage}</small>}
		</div>
	);
}
