// apps/sveltekit/src/lib/components/widgets/SelectWidget.svelte
<script lang="ts">
	import type { SelectWidget } from '@strivacity/sdk-svelte/client';
	import { useNativeLoginContext } from '@strivacity/sdk-svelte/client';

	let { formId, config }: { formId: string; config: SelectWidget } = $props();

	const context = useNativeLoginContext();
	const disabled = $derived(context.loading || !!config.readonly);
	const errorMessage = $derived(context.messages[formId]?.[config.id]?.text);
	const validator = $derived(config.validator);

	// svelte-ignore state_referenced_locally
	if (config.value) {
		context.setFormValue(formId, config.id, config.value);
	}

	function onChange(event: Event) {
		if (disabled) {
			return;
		}

		context.setFormValue(formId, config.id, (event.target as HTMLInputElement).value);
	}
</script>

<div data-widget="select" data-form-id={formId} data-widget-id={config.id}>
	{#if config.render?.type === 'radio'}
		{#each config.options as option (option.label)}
			<div class="group">
				{#if option.type === 'group'}
					<p>{option.label}</p>
					{#each option.options as subOption (subOption.value)}
						<div class="item">
							<input
								id={subOption.value}
								type="radio"
								name={config.id}
								readonly={disabled}
								value={subOption.value}
								checked={subOption.value === context.forms[formId]?.[config.id]}
								onchange={onChange}
							/>
							<label for={subOption.value}>{subOption.label}</label>
						</div>
					{/each}
				{:else}
					<input
						id={option.value}
						type="radio"
						name={config.id}
						value={option.value}
						checked={option.value === context.forms[formId]?.[config.id]}
						onchange={onChange}
					/>
					<label for={option.value}>{option.label}</label>
				{/if}
			</div>
		{/each}
		{#if errorMessage}
			<small class="error">{errorMessage}</small>
		{/if}
	{:else}
		{#if config.label}
			<label for={config.id} class="label">{config.label}</label>
		{/if}
		<select id={config.id} name={config.id} disabled={disabled} required={validator?.required} size="1" onchange={onChange}>
			{#each config.options as option (option.label)}
				{#if option.type === 'group'}
					<optgroup label={option.label}>
						{#each option.options as subOption (subOption.value)}
							<option value={subOption.value} selected={subOption.value === context.forms[formId]?.[config.id]}>
								{subOption.label}
							</option>
						{/each}
					</optgroup>
				{:else}
					<option value={option.value} selected={option.value === context.forms[formId]?.[config.id]}>
						{option.label}
					</option>
				{/if}
			{/each}
		</select>
		{#if errorMessage}
			<small class="error">{errorMessage}</small>
		{/if}
	{/if}
</div>

// apps/react/src/components/widgets/select.widget.tsx
import React, { useContext, useMemo } from 'react';
import type { SelectWidget } from '@strivacity/sdk-core';
import { NativeFlowContext } from '@strivacity/sdk-react';
import './select.widget.scss';

export function SelectWidget({ formId, config }: { formId: string; config: SelectWidget }) {
	const context = useContext(NativeFlowContext);
	const disabled = useMemo(() => !!context?.loading || !!config.readonly, [context?.loading, config.readonly]);
	const errorMessage = context?.messages[formId]?.[config.id]?.text;
	const value = context?.forms[formId]?.[config.id] as string | undefined;

	const onChange = (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
		if (disabled) {
			return;
		}

		context?.setFormValue(formId, config.id, event.target.value);
	};

	if (config.render.type === 'radio') {
		return (
			<div data-widget="select" data-form-id={formId} data-widget-id={config.id}>
				{config.options.map((option) =>
					option.type === 'group' ? (
						<div key={option.label} className="item">
							<p>{option.label}</p>
							{option.options.map((subOption) => (
								<div key={subOption.value} className="item">
									<input
										id={subOption.value}
										type="radio"
										name={config.id}
										readOnly={disabled}
										value={subOption.value}
										checked={subOption.value === value}
										onChange={(e) => onChange(e)}
									/>
									<label htmlFor={subOption.value}>{subOption.label}</label>
								</div>
							))}
						</div>
					) : (
						<div key={option.label} className="item">
							<input id={option.value} type="radio" name={config.id} value={option.value} checked={option.value === value} onChange={onChange} />
							<label htmlFor={option.value}>{option.label}</label>
						</div>
					),
				)}
				{errorMessage && <small className="error">{errorMessage}</small>}
			</div>
		);
	}

	return (
		<div data-widget="select" data-form-id={formId} data-widget-id={config.id}>
			{config.label && (
				<label htmlFor={config.id} className="label">
					{config.label}
				</label>
			)}
			<select
				id={config.id}
				name={config.id}
				disabled={disabled}
				required={config.validator?.required}
				size={1}
				value={value || ''}
				onChange={(e) => onChange(e)}
			>
				{config.options.map((option) =>
					option.type === 'group' ? (
						<optgroup key={option.label} label={option.label}>
							{option.options.map((subOption) => (
								<option key={subOption.value} value={subOption.value}>
									{subOption.label}
								</option>
							))}
						</optgroup>
					) : (
						<option key={option.label} value={option.value}>
							{option.label}
						</option>
					),
				)}
			</select>
			{errorMessage && <small className="error">{errorMessage}</small>}
		</div>
	);
}
