// apps/react/src/pages/Entry.tsx
import type { NativeFlow } from '@strivacity/sdk-react';
import { useStrivacity } from '@strivacity/sdk-react';
import { useEffect } from 'react';
import { useNavigate } from 'react-router';

export default function Entry() {
	const { loading, sdk, entry } = useStrivacity<NativeFlow>();
	const navigate = useNavigate();

	useEffect(() => {
		if (loading) {
			return;
		}

		entry()
			.then((params) => {
				const url = new URL('/login', globalThis.location.origin);
				url.search = new URLSearchParams(params).toString();
				globalThis.location.href = url.toString();
			})
			.catch((error) => {
				void navigate(`/error?message=${encodeURIComponent(error instanceof Error ? error.message : 'Unknown error')}`);
			});
	}, [loading, sdk, entry]);

	return null;
}

// apps/nuxt/app/pages/entry.vue
<script setup lang="ts">
import type { NativeFlow } from '@strivacity/sdk-nuxt';

const router = useRouter();
const { sdk, entry } = useStrivacity<NativeFlow>();

onMounted(async () => {
	try {
		const params = await entry();
		const url = new URL('/login', globalThis.location.origin);
		url.search = new URLSearchParams(params).toString();
		globalThis.location.href = url.toString();
	} catch (error) {
		await router.push(`/error?message=${encodeURIComponent(error instanceof Error ? error.message : 'Unknown error')}`);
	}
});
</script>

<template></template>
