// apps/next/src/app/login/page.tsx
'use client';

import { Suspense, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useStrivacity, StyLoginRenderer, FallbackError, type LoginFlowState } from '@strivacity/sdk-next';
import { widgets } from '../../components/widgets';

export default function Login() {
	const router = useRouter();
	const { options, login } = useStrivacity();
	const [sessionId, setSessionId] = useState<string | null>(null);

	useEffect(() => {
		if (window.location.search !== '') {
			const url = new URL(window.location.href);
			const sid = url.searchParams.get('session_id');
			setSessionId(sid);
			url.search = '';
			window.history.replaceState({}, '', url.toString());
		}
	}, []);

	useEffect(() => {
		// eslint-disable-next-line @typescript-eslint/no-floating-promises
		(async () => {
			if (options.mode === 'redirect') {
				await login();
			} else if (options.mode === 'popup') {
				await login();
				router.push('/profile');
			}
		})();
	}, []);

	const onLogin = () => {
		router.push('/profile');
	};
	const onFallback = (error: FallbackError) => {
		if (error.url) {
			// eslint-disable-next-line no-console
			console.log(`Fallback: ${error.url}`);
			window.location.href = error.url.toString();
		} else {
			// eslint-disable-next-line no-console
			console.error(`FallbackError without URL: ${error.message}`);
			alert(error);
		}
	};
	const onError = (error: string) => {
		// eslint-disable-next-line no-console
		console.error(`Error: ${error}`);
		alert(error);
	};
	const onGlobalMessage = (message: string) => {
		alert(message);
	};
	const onBlockReady = ({ previousState, state }: { previousState: LoginFlowState; state: LoginFlowState }) => {
		// eslint-disable-next-line no-console
		console.log('previousState', previousState);
		// eslint-disable-next-line no-console
		console.log('state', state);
	};

	return (
		<section>
			{options.mode === 'redirect' && <h1>Redirecting...</h1>}
			{options.mode === 'popup' && <h1>Loading...</h1>}
			{options.mode === 'native' && (
				<Suspense fallback={<span>Loading...</span>}>
					<StyLoginRenderer
						widgets={widgets}
						sessionId={sessionId}
						onFallback={onFallback}
						onLogin={() => void onLogin()}
						onError={onError}
						onGlobalMessage={onGlobalMessage}
						onBlockReady={onBlockReady}
					/>
				</Suspense>
			)}
		</section>
	);
}

// apps/nuxt/app/pages/login.vue
<script lang="ts" setup>
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { FallbackError, type LoginFlowState } from '@strivacity/sdk-core';

const router = useRouter();
const { options, login } = useStrivacity();
const sessionId = ref<string | null>(null);

if (location.search !== '') {
	const url = new URL(window.location.href);
	sessionId.value = url.searchParams.get('session_id');

	url.search = '';
	history.replaceState({}, '', url.toString());
}

onMounted(async () => {
	if (options.value.mode === 'redirect') {
		await login();
	} else if (options.value.mode === 'popup') {
		await login();
		await router.push('/profile');
	}
});

const onLogin = async () => {
	await router.push('/profile');
};
const onFallback = (error: FallbackError) => {
	if (error.url) {
		// eslint-disable-next-line no-console
		console.log(`Fallback: ${error.url}`);
		location.href = error.url.toString();
	} else {
		// eslint-disable-next-line no-console
		console.error(`FallbackError without URL: ${error.message}`);
		alert(error);
	}
};
const onError = (error: string) => {
	// eslint-disable-next-line no-console
	console.error(`Error: ${error}`);
	alert(error);
};
const onGlobalMessage = (message: string) => {
	alert(message);
};
const onBlockReady = ({ previousState, state }: { previousState: LoginFlowState; state: LoginFlowState }) => {
	// eslint-disable-next-line no-console
	console.log('previousState', previousState);
	// eslint-disable-next-line no-console
	console.log('state', state);
};
</script>

<template>
	<section>
		<h1 v-if="options.mode === 'redirect'">Redirecting...</h1>
		<h1 v-else-if="options.mode === 'popup'">Loading...</h1>
		<Suspense v-else-if="options.mode === 'native'">
			<template #default>
				<StyLoginRenderer
					:widgets="widgets"
					:session-id="sessionId"
					@fallback="onFallback"
					@login="onLogin"
					@error="onError"
					@global-message="onGlobalMessage"
					@block-ready="onBlockReady"
				/>
			</template>
			<template #fallback>
				<span>Loading...</span>
			</template>
		</Suspense>
	</section>
</template>

<style lang="scss">
.login-renderer {
	margin: 0 auto;
	width: 360px;
}
</style>
