// apps/vue/src/App.vue
<script setup lang="ts">
import { useStrivacity } from '@strivacity/sdk-vue';
import { computed } from 'vue';
import { RouterLink, RouterView } from 'vue-router';

const { isAuthenticated, idTokenClaims } = useStrivacity();

const name = computed(() => (isAuthenticated.value ? `${idTokenClaims.value?.given_name ?? ''} ${idTokenClaims.value?.family_name ?? ''}`.trim() : null));
</script>

<template>
	<header>
		<div>
			<strong v-if="isAuthenticated">Welcome, {{ name }}!</strong>
		</div>
		<div>
			<RouterLink to="/" data-button="home">Home</RouterLink>
			<template v-if="isAuthenticated">
				<RouterLink to="/profile" data-button="profile">Profile</RouterLink>
				<RouterLink to="/revoke" data-button="revoke">Revoke</RouterLink>
				<RouterLink to="/logout" data-button="logout">Logout</RouterLink>
			</template>
			<template v-else>
				<RouterLink to="/login" data-button="login">Login</RouterLink>
				<RouterLink to="/register" data-button="register">Register</RouterLink>
			</template>
		</div>
	</header>
	<RouterView />
</template>

// apps/ionic-react/src/components/App.tsx
import { useEffect, useState } from 'react';
import { Outlet, Link } from 'react-router';
import { useStrivacity } from '@strivacity/sdk-react';
import './App.css';

export const App = () => {
	const { loading, isAuthenticated, idTokenClaims } = useStrivacity();
	const [name, setName] = useState('');

	useEffect(() => {
		setName(`${idTokenClaims?.given_name ?? ''} ${idTokenClaims?.family_name ?? ''}`);
	}, [isAuthenticated, idTokenClaims]);

	return (
		<>
			<header>
				<div>{isAuthenticated ? <strong>Welcome, {name}!</strong> : loading ? <strong>Loading...</strong> : null}</div>
				<div>
					{!loading && (
						<>
							<Link to="/" data-button="home">
								Home
							</Link>
							{isAuthenticated ? (
								<>
									<Link to="/profile" data-button="profile">
										Profile
									</Link>
									<Link to="/revoke" data-button="revoke">
										Revoke
									</Link>
									<Link to="/logout" data-button="logout">
										Logout
									</Link>
								</>
							) : (
								<>
									<Link to="/login" data-button="login">
										Login
									</Link>
									<Link to="/register" data-button="register">
										Register
									</Link>
								</>
							)}
						</>
					)}
				</div>
			</header>
			<Outlet />
		</>
	);
};
