// apps/vue/src/pages/login.page.vue
<script lang="ts" setup>
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { FallbackError, useStrivacity, type ExtraRequestArgs, type LoginFlowState } from '@strivacity/sdk-vue';
import { widgets } from '../components/widgets';

const router = useRouter();
const { sdk, login } = useStrivacity();
const shortAppId = ref<string | null>(null);
const sessionId = ref<string | null>(null);
const extraParams: ExtraRequestArgs = {
	loginHint: import.meta.env.VITE_LOGIN_HINT,
	acrValues: import.meta.env.VITE_ACR_VALUES ? import.meta.env.VITE_ACR_VALUES?.split(' ') : undefined,
	uiLocales: import.meta.env.VITE_UI_LOCALES ? import.meta.env.VITE_UI_LOCALES?.split(' ') : undefined,
	audiences: import.meta.env.VITE_AUDIENCES ? import.meta.env.VITE_AUDIENCES?.split(' ') : undefined,
};

if (location.search !== '') {
	const url = new URL(window.location.href);
	shortAppId.value = url.searchParams.get('short_app_id');
	sessionId.value = url.searchParams.get('session_id');

	if (url.searchParams.has('language')) {
		extraParams.uiLocales = [url.searchParams.get('language')!];
	}

	url.search = '';
	history.replaceState({}, '', url.toString());
}

onMounted(async () => {
	if (sdk.options.mode === 'redirect') {
		await login(extraParams);
	} else if (sdk.options.mode === 'popup') {
		await login(extraParams);
		await router.push('/profile');
	}
});

const onLogin = async () => {
	await router.push('/profile');
};
const onFallback = (error: FallbackError) => {
	if (error.url) {
		location.href = error.url.toString();
	} else {
		alert(error);
	}
};
const onClose = () => {
	location.reload();
};
const onError = (error: string) => {
	alert(error);
};
const onGlobalMessage = (message: string) => {
	alert(message);
};
const onBlockReady = (_events: { previousState: LoginFlowState; state: LoginFlowState }) => {
	// You can handle block ready events here
};
</script>

<template>
	<section>
		<h1 v-if="sdk.options.mode === 'redirect'">Redirecting...</h1>
		<h1 v-else-if="sdk.options.mode === 'popup'">Loading...</h1>
		<template v-else-if="sdk.options.mode === 'embedded'">
			<sty-notifications></sty-notifications>
			<sty-login
				:shortAppId="shortAppId"
				:sessionId="sessionId"
				:params.prop="extraParams"
				@close="onClose"
				@login="onLogin"
				@error="onError($event.detail)"
				@block-ready="onBlockReady($event.detail)"
			></sty-login>
			<sty-language-selector></sty-language-selector>
		</template>
		<Suspense v-else-if="sdk.options.mode === 'native'">
			<template #default>
				<StyLoginRenderer
					:widgets="widgets"
					:session-id="sessionId"
					:params="extraParams"
					@fallback="onFallback"
					@close="onClose"
					@login="onLogin"
					@error="onError"
					@global-message="onGlobalMessage"
					@block-ready="onBlockReady"
				/>
			</template>
			<template #fallback>
				<span>Loading...</span>
			</template>
		</Suspense>
	</section>
</template>

<style lang="scss">
section:has(sty-login) {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
}

sty-language-selector {
	margin-block-start: 1rem;
}

.login-renderer {
	margin: 0 auto;
	width: 360px;
}
</style>

// apps/angular-bff/src/app/pages/login/login.page.ts
/* eslint-disable @typescript-eslint/no-explicit-any */

import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { Router } from '@angular/router';
import { SDKOptions, FallbackError, StyLoginRenderer, LoginFlowState, type ExtraRequestArgs, StrivacityAuthService } from '@strivacity/sdk-angular';
import { type ImportMeta } from '../../app.config';
import { widgets } from '../../components/widgets';

@Component({
	standalone: true,
	imports: [StyLoginRenderer],
	selector: 'app-login-page',
	templateUrl: './login.page.html',
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class LoginPage {
	readonly widgets = widgets;
	shortAppId: string | null = null;
	sessionId: string | null = null;
	mode: SDKOptions['mode'] = 'embedded';
	extraParams: ExtraRequestArgs = {
		loginHint: (import.meta as unknown as ImportMeta).env.VITE_LOGIN_HINT,
		acrValues: (import.meta as unknown as ImportMeta).env.VITE_ACR_VALUES ? (import.meta as unknown as ImportMeta).env.VITE_ACR_VALUES.split(' ') : undefined,
		uiLocales: (import.meta as unknown as ImportMeta).env.VITE_UI_LOCALES ? (import.meta as unknown as ImportMeta).env.VITE_UI_LOCALES.split(' ') : undefined,
		audiences: (import.meta as unknown as ImportMeta).env.VITE_AUDIENCES ? (import.meta as unknown as ImportMeta).env.VITE_AUDIENCES.split(' ') : undefined,
	};

	constructor(
		protected router: Router,
		protected strivacityAuthService: StrivacityAuthService,
	) {
		this.mode = (import.meta as unknown as ImportMeta).env.VITE_MODE;

		if (window.location.search !== '') {
			const url = new URL(window.location.href);
			this.sessionId = url.searchParams.get('session_id');

			if (url.searchParams.has('language')) {
				this.extraParams.uiLocales = [url.searchParams.get('language')!];
			}

			url.search = '';
			history.replaceState({}, '', url.toString());
		}
	}

	onLogin() {
		void this.router.navigateByUrl('/profile');
	}

	onFallback(error: FallbackError) {
		if (error.url) {
			location.href = error.url.toString();
		} else {
			alert(error);
		}
	}

	onClose() {
		location.reload();
	}

	onError(error: any) {
		alert(error);
	}

	onGlobalMessage(message: string) {
		alert(message);
	}

	onBlockReady(_events: { previousState: LoginFlowState; state: LoginFlowState }) {
		// You can handle block ready events here
	}
}
